In [1]:
import pandas as pd
import numpy as np

In [2]:
file = 'adult.csv'
my_data = pd.read_csv("adult.csv")

In [3]:
my_data.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [4]:
my_data.tail()

39      State-gov   77516    Bachelors   13        Never-married  \
32555  27        Private  257302   Assoc-acdm   12   Married-civ-spouse   
32556  40        Private  154374      HS-grad    9   Married-civ-spouse   
32557  58        Private  151910      HS-grad    9              Widowed   
32558  22        Private  201490      HS-grad    9        Never-married   
32559  52   Self-emp-inc  287927      HS-grad    9   Married-civ-spouse   

             Adm-clerical  Not-in-family   White     Male   2174   0   40  \
32555        Tech-support           Wife   White   Female      0   0   38   
32556   Machine-op-inspct        Husband   White     Male      0   0   40   
32557        Adm-clerical      Unmarried   White   Female      0   0   40   
32558        Adm-clerical      Own-child   White     Male      0   0   20   
32559     Exec-managerial           Wife   White   Female  15024   0   40   

        United-States   <=50K  
32555   United-States   <=50K  
32556   United-States    >50K  
32557   United-States   <=50K  
32558   United-States   <=50K  
32559   United-States    >50K

In [5]:
my_data.columns = ['age','workclass','fnlwgt','education','education_num','martial_status','occupation','relationship','race','sex','capital_gain','capital_loss','hours_per_week','native_country','income']

In [6]:
my_data.head()

age          workclass  fnlwgt   education  education_num  \
0   50   Self-emp-not-inc   83311   Bachelors             13   
1   38            Private  215646     HS-grad              9   
2   53            Private  234721        11th              7   
3   28            Private  338409   Bachelors             13   
4   37            Private  284582     Masters             14   

        martial_status          occupation    relationship    race      sex  \
0   Married-civ-spouse     Exec-managerial         Husband   White     Male   
1             Divorced   Handlers-cleaners   Not-in-family   White     Male   
2   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
3   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
4   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0             0             0              13   United-States   <=50K  
1             0             0              40   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40            Cuba   <=50K  
4             0             0              40   United-States   <=50K

In [7]:
my_data.tail()

age      workclass  fnlwgt    education  education_num  \
32555   27        Private  257302   Assoc-acdm             12   
32556   40        Private  154374      HS-grad              9   
32557   58        Private  151910      HS-grad              9   
32558   22        Private  201490      HS-grad              9   
32559   52   Self-emp-inc  287927      HS-grad              9   

            martial_status          occupation relationship    race      sex  \
32555   Married-civ-spouse        Tech-support         Wife   White   Female   
32556   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32557              Widowed        Adm-clerical    Unmarried   White   Female   
32558        Never-married        Adm-clerical    Own-child   White     Male   
32559   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital_gain  capital_loss  hours_per_week  native_country  income  
32555             0             0              38   United-States   <=50K  
32556             0             0              40   United-States    >50K  
32557             0             0              40   United-States   <=50K  
32558             0             0              20   United-States   <=50K  
32559         15024             0              40   United-States    >50K

In [8]:
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32560 non-null  int64 
 1   workclass       32560 non-null  object
 2   fnlwgt          32560 non-null  int64 
 3   education       32560 non-null  object
 4   education_num   32560 non-null  int64 
 5   martial_status  32560 non-null  object
 6   occupation      32560 non-null  object
 7   relationship    32560 non-null  object
 8   race            32560 non-null  object
 9   sex             32560 non-null  object
 10  capital_gain    32560 non-null  int64 
 11  capital_loss    32560 non-null  int64 
 12  hours_per_week  32560 non-null  int64 
 13  native_country  32560 non-null  object
 14  income          32560 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [9]:
my_data['workclass'].value_counts()

 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1297
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: workclass, dtype: int64

In [10]:
my_data['martial_status'].value_counts()

 Married-civ-spouse       14976
 Never-married            10682
 Divorced                  4443
 Separated                 1025
 Widowed                    993
 Married-spouse-absent      418
 Married-AF-spouse           23
Name: martial_status, dtype: int64

In [11]:
my_data['relationship'].value_counts()

 Husband           13193
 Not-in-family      8304
 Own-child          5068
 Unmarried          3446
 Wife               1568
 Other-relative      981
Name: relationship, dtype: int64

In [12]:
my_data['race'].value_counts()

 White                 27815
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
Name: race, dtype: int64

In [13]:
my_data['sex'].value_counts()

 Male      21789
 Female    10771
Name: sex, dtype: int64

In [14]:
my_data['education'].value_counts()

 HS-grad         10501
 Some-college     7291
 Bachelors        5354
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: education, dtype: int64

In [15]:
my_data['income'].value_counts()

 <=50K    24719
 >50K      7841
Name: income, dtype: int64

In [16]:
my_data.iloc[[26]]

age workclass  fnlwgt      education  education_num       martial_status  \
26   54         ?  180211   Some-college             10   Married-civ-spouse   

   occupation relationship                 race    sex  capital_gain  \
26          ?      Husband   Asian-Pac-Islander   Male             0   

    capital_loss  hours_per_week native_country income  
26             0              60          South   >50K

In [17]:
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32560 non-null  int64 
 1   workclass       32560 non-null  object
 2   fnlwgt          32560 non-null  int64 
 3   education       32560 non-null  object
 4   education_num   32560 non-null  int64 
 5   martial_status  32560 non-null  object
 6   occupation      32560 non-null  object
 7   relationship    32560 non-null  object
 8   race            32560 non-null  object
 9   sex             32560 non-null  object
 10  capital_gain    32560 non-null  int64 
 11  capital_loss    32560 non-null  int64 
 12  hours_per_week  32560 non-null  int64 
 13  native_country  32560 non-null  object
 14  income          32560 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [18]:
my_data.iloc[[26]]

age workclass  fnlwgt      education  education_num       martial_status  \
26   54         ?  180211   Some-college             10   Married-civ-spouse   

   occupation relationship                 race    sex  capital_gain  \
26          ?      Husband   Asian-Pac-Islander   Male             0   

    capital_loss  hours_per_week native_country income  
26             0              60          South   >50K

In [19]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

my_cols = ['workclass', 'education', 'martial_status', 'occupation', 'relationship', 'race', 'sex', 'native_country']

for col in my_cols:
    encoder1 = LabelEncoder()
    my_data[col] = encoder1.fit_transform(my_data[col])
    my_data[col]

    #encoder2 = OneHotEncoder()
    #my_data[col] = pd.DataFrame(encoder2.fit_transform(my_data[[col]]))


In [20]:
my_data.head()

age  workclass  fnlwgt  education  education_num  martial_status  \
0   50          6   83311          9             13               2   
1   38          4  215646         11              9               0   
2   53          4  234721          1              7               2   
3   28          4  338409          9             13               2   
4   37          4  284582         12             14               2   

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           4             0     4    1             0             0   
1           6             1     4    1             0             0   
2           6             0     2    1             0             0   
3          10             5     2    0             0             0   
4           4             5     4    0             0             0   

   hours_per_week  native_country  income  
0              13              39   <=50K  
1              40              39   <=50K  
2              40              39   <=50K  
3              40               5   <=50K  
4              40              39   <=50K

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_features = list(my_data.drop('income', axis=1))
X_train, x_test, Y_train, y_test = train_test_split(my_data[X_features], my_data['income'], test_size=0.2, random_state=42)

In [23]:
X_train.head()

age  workclass  fnlwgt  education  education_num  martial_status  \
24639   20          4  385077          2              8               4   
5514    21          7  140764         15             10               4   
19777   64          4  312242         15             10               6   
10781   26          4  227489         11              9               4   
32239   21          4  180190          8             11               2   

       occupation  relationship  race  sex  capital_gain  capital_loss  \
24639           7             3     4    1             0             0   
5514            1             3     4    0             0             0   
19777           4             1     4    0             0             0   
10781          13             2     2    1             0             0   
32239           5             0     4    1             0             0   

       hours_per_week  native_country  
24639              40              39  
5514               12              39  
19777               3              39  
10781              40               0  
32239              46              39

In [24]:
x_test.head()

age  workclass  fnlwgt  education  education_num  martial_status  \
14160   38          4  680390         11              9               0   
27047   45          7   50567         11              9               2   
28867   29          4  185908          9             13               2   
5667    51          4  306108         10             16               4   
7827    46          4  124071         12             14               6   

       occupation  relationship  race  sex  capital_gain  capital_loss  \
14160           1             4     4    0             0             0   
27047           4             5     4    0             0             0   
28867           4             0     2    1             0             0   
5667           10             1     4    1             0             0   
7827           10             1     4    0             0             0   

       hours_per_week  native_country  
14160              20              39  
27047              40              39  
28867              55              39  
5667               40              39  
7827               44              39

In [25]:
from sklearn.tree import DecisionTreeClassifier

In [26]:
decision_tree_model = DecisionTreeClassifier()

In [27]:
decision_tree_model.fit(X_train,Y_train)

DecisionTreeClassifier()

In [28]:


from sklearn.metrics import accuracy_score, confusion_matrix

In [29]:
predicted_score = decision_tree_model.predict(x_test)
score = accuracy_score(y_test, predicted_score)
print(score)

0.8066646191646192


In [30]:
print('predicted values:/t', predicted_score[:10])
print('real values:/t', np.array(y_test[:10]))

predicted values:/t [' <=50K' ' >50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' >50K' ' <=50K']
real values:/t [' <=50K' ' <=50K' ' >50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' <=50K' ' <=50K']


In [31]:
confusion_matrix(y_test, predicted_score)

array([[4251,  661],
       [ 598, 1002]], dtype=int64)

In [32]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predicted_score))

              precision    recall  f1-score   support

       <=50K       0.88      0.87      0.87      4912
        >50K       0.60      0.63      0.61      1600

    accuracy                           0.81      6512
   macro avg       0.74      0.75      0.74      6512
weighted avg       0.81      0.81      0.81      6512



In [33]:
from sklearn.ensemble import RandomForestClassifier  
random_classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
random_classifier.fit(X_train, Y_train)  

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [34]:
predicted_score = random_classifier.predict(x_test)
score = accuracy_score(y_test, predicted_score)
print(score)

0.8449017199017199


In [35]:
print('predicted values:/t', predicted_score[:10])
print('real values:/t', np.array(y_test[:10]))

predicted values:/t [' <=50K' ' <=50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' >50K' ' <=50K']
real values:/t [' <=50K' ' <=50K' ' >50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' <=50K' ' <=50K']


In [36]:
confusion_matrix(y_test, predicted_score)

array([[4579,  333],
       [ 677,  923]], dtype=int64)

In [38]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predicted_score))

              precision    recall  f1-score   support

       <=50K       0.87      0.93      0.90      4912
        >50K       0.73      0.58      0.65      1600

    accuracy                           0.84      6512
   macro avg       0.80      0.75      0.77      6512
weighted avg       0.84      0.84      0.84      6512



In [39]:
from sklearn.neighbors import KNeighborsClassifier  
KNN_classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
KNN_classifier.fit(X_train, Y_train)  

KNeighborsClassifier()

In [40]:
predicted_score = random_classifier.predict(x_test)
score = accuracy_score(y_test, predicted_score)
print(score)

0.8449017199017199


In [41]:
print('predicted values:/t', predicted_score[:10])
print('real values:/t', np.array(y_test[:10]))

predicted values:/t [' <=50K' ' <=50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' >50K' ' <=50K']
real values:/t [' <=50K' ' <=50K' ' >50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' <=50K' ' <=50K']


In [42]:
confusion_matrix(y_test, predicted_score)

array([[4579,  333],
       [ 677,  923]], dtype=int64)

In [43]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predicted_score))

              precision    recall  f1-score   support

       <=50K       0.87      0.93      0.90      4912
        >50K       0.73      0.58      0.65      1600

    accuracy                           0.84      6512
   macro avg       0.80      0.75      0.77      6512
weighted avg       0.84      0.84      0.84      6512



In [44]:
from sklearn.linear_model import LogisticRegression  
logistic= LogisticRegression(random_state=0,max_iter=1000)  
logistic.fit(X_train, Y_train) 

LogisticRegression(max_iter=1000, random_state=0)

In [45]:
predicted_score = random_classifier.predict(x_test)
score = accuracy_score(y_test, predicted_score)
print(score)

0.8449017199017199


In [46]:
print('predicted values:/t', predicted_score[:10])
print('real values:/t', np.array(y_test[:10]))

predicted values:/t [' <=50K' ' <=50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' >50K' ' <=50K']
real values:/t [' <=50K' ' <=50K' ' >50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' <=50K' ' <=50K']


In [47]:
confusion_matrix(y_test, predicted_score)

array([[4579,  333],
       [ 677,  923]], dtype=int64)

In [49]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predicted_score))

              precision    recall  f1-score   support

       <=50K       0.87      0.93      0.90      4912
        >50K       0.73      0.58      0.65      1600

    accuracy                           0.84      6512
   macro avg       0.80      0.75      0.77      6512
weighted avg       0.84      0.84      0.84      6512



In [50]:
from sklearn.svm import SVC
svc_model = SVC( random_state=0)  
svc_model.fit(X_train, Y_train)

SVC(random_state=0)

In [51]:
predicted_score = random_classifier.predict(x_test)
score = accuracy_score(y_test, predicted_score)
print(score)

0.8449017199017199


In [52]:
print('predicted values:/t', predicted_score[:10])
print('real values:/t', np.array(y_test[:10]))

predicted values:/t [' <=50K' ' <=50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' >50K' ' <=50K']
real values:/t [' <=50K' ' <=50K' ' >50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' <=50K' ' <=50K']


In [53]:
confusion_matrix(y_test, predicted_score)

array([[4579,  333],
       [ 677,  923]], dtype=int64)

In [54]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predicted_score))

              precision    recall  f1-score   support

       <=50K       0.87      0.93      0.90      4912
        >50K       0.73      0.58      0.65      1600

    accuracy                           0.84      6512
   macro avg       0.80      0.75      0.77      6512
weighted avg       0.84      0.84      0.84      6512



In [ ]:
#PERCENTAGE OF EACH MODEL

In [1]:
#Random Forest Classifier

In [2]:
(333+677)/(333+677+923+4579)*100

15.509828009828011

In [3]:
#Logistic Regression


In [4]:
(333+677)/(333+677+923+4579)*100

15.509828009828011

In [5]:
#KNN Classifier


In [6]:
(333+677)/(333+677+923+4579)*100

15.509828009828011

In [7]:
#SVC

In [8]:
(333+677)/(333+677+923+4579)*100

15.509828009828011

In [9]:
#Decision Tree

In [10]:
(598+661)/(598+661+1002+4251)*100

19.333538083538084

In [13]:
#BEST ACCURACY
#1. Random Forest Classifier - 15.509828009828011
#2. Logistic Regression - 15.509828009828011
#3. KNN Classifier - 15.509828009828011
#4. SVC - 15.509828009828011
#5. Decision Tree - 19.333538083538084
